[tool.poetry]
name = "openbb-yfinance"
version = "0.0.0a1"
description = "yfinance integration for OpenBB SDK"
authors = ["OpenBB Team <hello@openbb.co>"]
readme = "README.md"
packages = [{ include = "openbb_yfinance" }]

[tool.poetry.dependencies]
python = "^3.8"
yfinance="^0.2.27"
openbb-core = {version = "^0.0.0a5", source = "test-pypi"}

[[tool.poetry.source]]
name = "test-pypi"
url = "https://test.pypi.org/simple/"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_provider_extension"]
yfinance = "openbb_yfinance:yfinance_provider"
