[tool.poetry]
name = "openbb"
version = "4.0.0a0"
description = "OpenBB"
authors = ["OpenBB Team <hello@openbb.co>"]
readme = "README.md"
packages = [{ include = "openbb" }]

[tool.poetry.dependencies]
python = ">=3.8,<3.12"
openbb-core = { path = "./sdk/core" }
openbb-stocks = { path = "./extensions/stocks" }
openbb-etf = { path = "./extensions/etf" }
openbb-crypto = { path = "./extensions/crypto" }
openbb-forex = { path = "./extensions/forex" }
openbb-futures = { path = "./extensions/futures" }
openbb-news = { path = "./extensions/news" }
openbb-economy = { path = "./extensions/economy" }
openbb-fixedincome = { path = "./extensions/fixedincome" }
openbb-charting = { path = "./extensions/charting"}
openbb-alpha-vantage = { path = "./providers/alpha_vantage" }
openbb-benzinga = { path = "./providers/benzinga" }
openbb-cboe = { path = "./providers/cboe"}
openbb-fmp = { path = "./providers/fmp" }
openbb-fred = { path = "./providers/fred" }
openbb-intrinio = { path = "./providers/intrinio" }
openbb-polygon = { path = "./providers/polygon" }
openbb-quandl = { path = "./providers/quandl" }
openbb-yfinance = { path = "./providers/yfinance" }

[tool.poetry.group.dev.dependencies]
pytest = "^6.2.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
