[tool.poetry]
name = "openbb-biztoc"
version = "0.1.0"
description = ""
authors = ["OpenBB Team <hello@openbb.co>"]
readme = "README.md"
packages = [{ include = "openbb_biztoc" }]

[tool.poetry.dependencies]
python = "^3.8"
openbb-provider = { path = "../../sdk/provider" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_provider_extension"]
cboe = "openbb_biztoc:biztoc_provider"
